build:
    environment:
        selenium: false
        memcached: false
        postgresql: false
        php:
            version: 7.1.9

    cache:
        directories:
            - ~/eelly

    dependencies:
        override:
            - composer install --prefer-source --no-interaction
        after:
            - vendor/bin/install-phalcon.sh 3.2.x
            - php -r "echo \Phalcon\Version::get();"